import { mkdirSync, writeFileSync } from "fs";
import type { KnowledgeItem } from "../../storage/repository.js";

export function projectToMarkdown(items: KnowledgeItem[], generatedDir: string, compilerVersion: string): void {
  mkdirSync(generatedDir, { recursive: true });

  const active = items.filter((i) => i.status === "active");
  const timestamp = new Date().toISOString();
  const header = (title: string) =>
    `<!-- AUTO-GENERATED BY LOOP v${compilerVersion} — DO NOT EDIT -->\n<!-- Source of truth: .loop/loop.db -->\n<!-- To add permanent items: loop add-knowledge -->\n<!-- Last compiled: ${timestamp} | ${active.length} active items -->\n\n# ${title}\n\n`;

  const rules = active.filter((i) => i.type === "rule").sort((a, b) => confidenceOrder(b) - confidenceOrder(a));
  const lessons = active.filter((i) => i.type === "lesson").sort((a, b) => confidenceOrder(b) - confidenceOrder(a));
  const decisions = active.filter((i) => i.type === "decision").sort((a, b) => confidenceOrder(b) - confidenceOrder(a));
  const context = active.filter((i) => i.type === "context").sort((a, b) => b.lastSeenAt - a.lastSeenAt);

  writeFileSync(
    `${generatedDir}/RULES.md`,
    header("Rules") + formatItems(rules),
    "utf-8"
  );
  writeFileSync(
    `${generatedDir}/LESSONS.md`,
    header("Lessons") + formatItems(lessons),
    "utf-8"
  );
  writeFileSync(
    `${generatedDir}/DECISIONS.md`,
    header("Decisions") + formatItems(decisions),
    "utf-8"
  );
  writeFileSync(
    `${generatedDir}/CONTEXT.md`,
    header("Context") + formatItems(context),
    "utf-8"
  );
}

function confidenceOrder(item: KnowledgeItem): number {
  switch (item.confidence) {
    case "high": return 3;
    case "medium": return 2;
    case "low": return 1;
  }
}

function formatItems(items: KnowledgeItem[]): string {
  if (items.length === 0) return "_No items yet._\n";
  return items
    .map((i) => {
      const badge = i.enforce ? " 🛡️" : "";
      const conf = `(${i.confidence}, ${i.observationCount}×)`;
      return `- ${i.content}${badge} ${conf}`;
    })
    .join("\n") + "\n";
}
