import { existsSync, mkdirSync, writeFileSync, readFileSync } from "fs";
import { join } from "path";
import { homedir } from "os";
import { findProjectRoot, getLoopDir } from "./utils/paths.js";
import { SqliteKnowledgeRepository } from "./storage/sqlite.js";

export async function initProject(opts: { cursor?: boolean } = {}): Promise<void> {
  const projectRoot = findProjectRoot();
  const loopDir = getLoopDir(projectRoot);
  const generatedDir = join(loopDir, "generated");

  mkdirSync(generatedDir, { recursive: true });

  const dbPath = join(loopDir, "loop.db");
  const repo = new SqliteKnowledgeRepository(dbPath);
  repo.close();

  const configPath = join(loopDir, "config.json");
  if (!existsSync(configPath)) {
    writeFileSync(configPath, JSON.stringify({ project: projectRoot.split("/").pop(), reviewMode: false }, null, 2));
  }

  for (const file of ["RULES.md", "LESSONS.md", "DECISIONS.md", "CONTEXT.md"]) {
    const filePath = join(generatedDir, file);
    if (!existsSync(filePath)) {
      writeFileSync(filePath, `<!-- AUTO-GENERATED BY LOOP — DO NOT EDIT -->\n\nNo items yet. Run a session and let Loop compile.\n`);
    }
  }

  const injectedPath = join(loopDir, "injected-context.md");
  if (!existsSync(injectedPath)) {
    writeFileSync(injectedPath, `<!-- Loop context — not yet compiled -->\n\nLoop has not compiled any sessions yet.\n`);
  }

  const claudeMdPath = join(projectRoot, "CLAUDE.md");
  const importLine = "@.loop/injected-context.md";
  if (existsSync(claudeMdPath)) {
    const content = readFileSync(claudeMdPath, "utf-8");
    if (!content.includes(importLine)) {
      writeFileSync(claudeMdPath, content.trimEnd() + `\n\n${importLine}\n`);
    }
  } else {
    writeFileSync(claudeMdPath, `# Project Instructions\n\n${importLine}\n`);
  }

  registerHooks();

  console.log(`Loop initialized in ${loopDir}`);
  console.log(`  Database: ${dbPath}`);
  console.log(`  Generated: ${generatedDir}`);
  console.log(`  Hooks registered in ~/.claude/settings.json`);
  console.log(`  MCP server: add to your IDE config or run 'loop serve'`);
}

function registerHooks(): void {
  const settingsPath = join(homedir(), ".claude", "settings.json");
  let settings: Record<string, unknown> = {};

  if (existsSync(settingsPath)) {
    try {
      settings = JSON.parse(readFileSync(settingsPath, "utf-8"));
    } catch {
      settings = {};
    }
  }

  if (!settings.hooks) settings.hooks = {};
  const hooks = settings.hooks as Record<string, unknown[]>;

  const loopHooks: Record<string, unknown[]> = {
    Stop: [{ matcher: "", hooks: [{ type: "command", command: "npx loop compile" }] }],
    SessionStart: [{ matcher: "", hooks: [{ type: "command", command: "npx loop inject" }] }],
    PreToolUse: [{ matcher: "", hooks: [{ type: "command", command: "npx loop enforce" }] }],
  };

  for (const [event, hookConfig] of Object.entries(loopHooks)) {
    if (!hooks[event]) hooks[event] = [];
    const existing = hooks[event] as Array<{ hooks?: Array<{ command?: string }> }>;
    const hasLoop = existing.some((h) =>
      h.hooks?.some((hh) => hh.command?.includes("npx loop"))
    );
    if (!hasLoop) {
      hooks[event].push(...hookConfig);
    }
  }

  mkdirSync(join(settingsPath, ".."), { recursive: true });
  writeFileSync(settingsPath, JSON.stringify(settings, null, 2));
}
